artifact_location: /home/aurelien/code/baptperr/clairvoyance - Copie/runs/mlflow/0
creation_time: 1764883552625
experiment_id: '0'
last_update_time: 1764883552625
lifecycle_stage: active
name: Default
